version: '3.7'
services:

  redis-master:
    image: 'bitnami/redis:latest'
    privileged: true
    user: root
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=${redis_password}
    ports:
      - '6379:6379'
    volumes:
      - '~/redis:/bitnami'

  redis-replica:
    image: 'bitnami/redis:latest'
    privileged: true
    user: root
    ports:
      - '6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=${redis_password}
      - REDIS_PASSWORD=${redis_password}

